### ISSUE TITLE
2018-11-30[Edison Yin] Singleton

### ISSUE THREAD

**Issue by EdisonYin** [EdisonYin/micro-service#2]
Singleton Model
`
import java.io.ObjectStreamException;
import java.io.Serializable;

public class Singleton implements Serializable{

	private Singleton() {
        if (SingleBuilder.INSTANCE != null) {
            throw new IllegalStateException();
        }
	}
	
	private static class SingleBuilder {
		public static final Singleton INSTANCE =  new Singleton();
	}
	
    public static Singleton getInstance() {
        return SingleBuilder.INSTANCE;
    }
    
    protected Object readResolve()throws ObjectStreamException {
        return SingleBuilder.INSTANCE;
    }

}`

Test main
`
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;

public class testSingleton {

	public static void main(String[] args) {
		// 是否为同一对象
		Singleton singletonA = Singleton.getInstance();
		Singleton singletonB = Singleton.getInstance();
		
		System.out.println(" singletonA " + singletonA.hashCode() + " singletonB " + singletonB.hashCode());
		
		// 可否反序列化？
		
        //Write Obj to file
        ObjectOutputStream oos;
		try {
			oos = new ObjectOutputStream(new FileOutputStream("tempFile"));
	        oos.writeObject(Singleton.getInstance());
	        //Read Obj from file
	        File file = new File("tempFile");
	        ObjectInputStream ois =  new ObjectInputStream(new FileInputStream(file));
	        Singleton newInstance = (Singleton) ois.readObject();
	        //判断是否是同一个对象
	        System.out.println(newInstance == singletonA);
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		Class slClass = Singleton.class;
		
		
		try {
			Constructor con = slClass.getDeclaredConstructor();
			 con.setAccessible(true);
			Singleton singletonC = (Singleton) con.newInstance();
			System.out.println(singletonC == singletonA);
		} catch (NoSuchMethodException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SecurityException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InstantiationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalArgumentException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvocationTargetException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
	
}
`

output
` singletonA 366712642 singletonB 366712642
true
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at test.testSingleton.main(testSingleton.java:52)
Caused by: java.lang.IllegalStateException
	at test.Singleton.<init>(Singleton.java:10)
	... 5 more
`

**Comment by EdisonYin** [comment]
https://www.callicoder.com/java-singleton-design-pattern-example/
